package BankEntity;
// Generated Jun 5, 2011 5:23:41 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String userName;
     private String password;
     private int bankAccNumber;
     private String emailId;
     private String contactId;
     private Set<Banktrans> banktranses = new HashSet<Banktrans>(0);

    public Customer() {
    }

	
    public Customer(String userName, String password, int bankAccNumber, String emailId, String contactId) {
        this.userName = userName;
        this.password = password;
        this.bankAccNumber = bankAccNumber;
        this.emailId = emailId;
        this.contactId = contactId;
    }
    public Customer(String userName, String password, int bankAccNumber, String emailId, String contactId, Set<Banktrans> banktranses) {
       this.userName = userName;
       this.password = password;
       this.bankAccNumber = bankAccNumber;
       this.emailId = emailId;
       this.contactId = contactId;
       this.banktranses = banktranses;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getBankAccNumber() {
        return this.bankAccNumber;
    }
    
    public void setBankAccNumber(int bankAccNumber) {
        this.bankAccNumber = bankAccNumber;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getContactId() {
        return this.contactId;
    }
    
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }
    public Set<Banktrans> getBanktranses() {
        return this.banktranses;
    }
    
    public void setBanktranses(Set<Banktrans> banktranses) {
        this.banktranses = banktranses;
    }




}


